// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnp07w58LAi_P1-GHi6HJiAPMrIwQrjvo',
    appId: '1:464192358000:web:c52033307f0feff964d6b5',
    messagingSenderId: '464192358000',
    projectId: 'sedi-app',
    authDomain: 'sedi-app.firebaseapp.com',
    storageBucket: 'sedi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDsaZIzKizlbs1abvGg5IHcXFZBxfmIOM',
    appId: '1:464192358000:android:e699a71460ed8c2a64d6b5',
    messagingSenderId: '464192358000',
    projectId: 'sedi-app',
    storageBucket: 'sedi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD41s5YLdjyV-e2Jkgm11Vhc_GPT-r0Wcg',
    appId: '1:464192358000:ios:44f68ad6526fa8ee64d6b5',
    messagingSenderId: '464192358000',
    projectId: 'sedi-app',
    storageBucket: 'sedi-app.firebasestorage.app',
    iosBundleId: 'com.example.sediDiabetesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD41s5YLdjyV-e2Jkgm11Vhc_GPT-r0Wcg',
    appId: '1:464192358000:ios:44f68ad6526fa8ee64d6b5',
    messagingSenderId: '464192358000',
    projectId: 'sedi-app',
    storageBucket: 'sedi-app.firebasestorage.app',
    iosBundleId: 'com.example.sediDiabetesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnp07w58LAi_P1-GHi6HJiAPMrIwQrjvo',
    appId: '1:464192358000:web:bc816f3c4df3d64464d6b5',
    messagingSenderId: '464192358000',
    projectId: 'sedi-app',
    authDomain: 'sedi-app.firebaseapp.com',
    storageBucket: 'sedi-app.firebasestorage.app',
  );
}
